apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extension-registry-cache-admission
webhooks:
- name: validation.registry.cache.extension.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  # Please make sure you are running `gardener@v1.42` or later before enabling this object selector.
  objectSelector:
    matchLabels:
      extensions.extensions.gardener.cloud/registry-cache: "true"
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://host.docker.internal:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrakNDQWVLZ0F3SUJBZ0lRRmtkOUZJWUFiV2tXQUtTRjY5bW5ZVEFOQmdrcWhraUc5dzBCQVFzRkFEQVgKTVJVd0V3WURWUVFERXd4bllYSmtaVzVsY2kxa1pYWXdIaGNOTWpJd09USTNNVE15T1RJMVdoY05Nekl3T1RJMApNVE15T1RJMVdqQVhNUlV3RXdZRFZRUURFd3huWVhKa1pXNWxjaTFrWlhZd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFER0JrNkdtMCtFVEg5WlFlanlYa2RGMUViU2VmTGxBaENLZTRWbk9SWUEKakgwTFlrRDZMYis3VDc3Y2piTHFBbDJZQU1JTzVVd0NlR0NXdnZIWHA1RHkxV1k2eW9EVHZxT2JtZFV2WXEzawpPTU1qRnQyTkl4dVRQNFVFcDlpemxQUWhuUml4bms4N0pDajRocS9VZUIyVkxtUm1uVVQyWU5md3NCcXlMbmZSCks4NTNKNXZ3ZWNFU1hVdlgxbmZLb1dFemFMWmVqbndsc3JHaEppNCtTZ0hPMWtmZVdxaEhtdFJUek8wa0UybnEKQWExUmZRMFhVMVYxR0tlUHJUQjBWQ01yS2F4bmNqaC9IY3NWOXhDZ1RRd3ZVdGJYQmo0ek9QYmRReVh4L3RuKwpNTmpTUU5mVzdRbWRkK1ZiUnhaMDZjMmM0YzYwcSt2ZkR6eWlKVnlSc2pBbEFnTUJBQUdqUWpCQU1BNEdBMVVkCkR3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUVU0MHlHVkxBYnNHMjAKWG5pRkZQTWpYa2Q1cERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUNaL0ovWVVNejY3d0M2SitzUk1HOS9YNwpxejQ5TXJkdmQ4MGpkZUlPYXYwR2U0bzlCSEFSODZMb053bzdaK0xuRG1NWXJIK3dyaklObDBMdE4yQURtR1BxCmZDbndlR3c2NmUvdmJ3WVRBRmlwREZlUDFwenNQcEJWbGtsSTdFRStIcmRWUTNDSUljeFhwdHpGaVJpNXRhMDQKa252SmNrQTVPeFRQQ2I5dG9hV21MdDVDVk5Id0RiTko3Q1NXK3RBT0pLcGZaTEtxd1lqOXlGWXhhcE5COVU4Ygpwek56WGhGUkJZUVpXT3ZNbGxrdzBxa09TV0Q5Ri9LQVdlVWNUeDk0NFkrTEErL1RxS1NVY2JKSHVmc0luL1RqClFyb3hMVXA5djRiencwZVZnZmhjZExhdXFwaEZ3WVZuaXp2ZWJLNmdUYVZiTmFETmlWZXlhY0dMQi9TSXlnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
