apiVersion: v1
kind: Secret
metadata:
  name: gardener-extension-registry-cache-admission-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ required ".Values.global.webhookConfig.tls.crt is required" .Values.global.webhookConfig.tls.crt | b64enc }}
  tls.key: {{ required ".Values.global.webhookConfig.tls.key is required" .Values.global.webhookConfig.tls.key | b64enc }}
