---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-registry-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-registry-cache
    helm.sh/chart: gardener-extension-registry-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
